name: 481_repo
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - requests
  - numpy
  - opencv
  - pillow
  - selenium
  - flask
  - flask-cors
  - tqdm
  - nltk
  - ollama-python
  - beautifulsoup4
  - dspy-ai
