name: cse481
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - requests
  - numpy
  - opencv
  - pillow
  - selenium
  - flask
  - flask-cors
  - tqdm
  - ollama-python
  - beautifulsoup4
